server:
  port : 8085
  servlet:
    context-path: /api/${parcom.api.version}

parcom:
  api:
    version: v1
  services:
    -
      name: user-cache
      host: pc-user-cache
      port: 8086
      version: v1
spring:
  application.name: pc-notifier_agent_push
  hateoas:
    use-hal-as-default-json-media-type: false

